priority_transliterations = {
    'lote': 'လုပ်',
    'nay': 'နေ',
    'pe' : 'ပြီ',
    'ya': 'ရ',
    "kyay": "ကျေး",
    "zu": "ဇူး",
    "tin": "တင်",
    "thu": "သူ",
    "nay": "နေ",
    "pyi": "ပြီ",
    "lay": "လေ",
    "pyaw": "ပြော",
    "yat": "ရပ်",
    "ya": "ရ",
    "tha": "သ",
    "pya": "ပြ",
    "mya": "မြ",
    "nya": "ည",
    "sha": "ရှ",
}